# -*- mode: ruby -*-
# vi: set ft=ruby :

# Multihost mode 'yes'
#multihost = ENV['MULTIHOST']

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Global network config
  #config.vm.network "private_network", type: "dhcp"

  # If mulstihost is true creates leader and worker nodes
  #if multihost == "yes"

    # Leader node
    1.upto(1) do |i|
      config.vm.define "leader-#{i}" do |node|
        config.vm.hostname = "leader-#{i}"
        config.vm.provider :virtualbox do |vm|
          vm.memory = 512
          vm.cpus = 1
        end

        node.vm.network "private_network", ip: "10.0.2.15"

       # Salt Provisioner
        config.vm.provision :salt do |salt|
          salt.minion_config = "./leader/etc/salt/minion"
          salt.run_highstate = false
          salt.install_type = "git"
          salt.install_args = "v2018.3.0"
          salt.verbose = true
        end

        # Leader provision
        config.vm.provision "shell", path: "../scripts/apply-formulas.sh"
        config.vm.provision "shell", path: "../scripts/test-hashistack.sh"
        config.vm.provision "shell", path: "../scripts/core-leader.sh", args: "LEADER_ID=#{i}"
        config.vm.provision "shell", path: "../scripts/test-nomad-job.sh"
      end
    end

    # Worker node
    1.upto(1) do |i|
      config.vm.define "worker-#{i}" do |node|
        config.vm.hostname = "worker-#{i}"
        config.vm.provider :virtualbox do |vm|
          vm.memory = 2564
          vm.cpus = 1
        end

        node.vm.network "private_network", ip: "10.0.2.16"
        # Salt Provisioner
        config.vm.provision :salt do |salt|
          salt.minion_config = "./worker/etc/salt/minion"
          salt.run_highstate = true
          salt.install_type = "git"
          salt.install_args = "v2018.3.0"
          salt.verbose = true
        end

        # Worker provision
        config.vm.provision "shell", path: "../scripts/apply-formulas.sh"
        config.vm.provision "shell", path: "../scripts/test-hashistack.sh"
        config.vm.provision "shell", path: "../scripts/core-worker.sh", args: "WORKER_ID=#{i}"
        config.vm.provision "shell", path: "../scripts/test-nomad-job.sh"
      end
    end

end
