# top.sls - map to formula/states
applications:
  - python.pip
  - apps.common
  - aws.cli.install
  - ufw.default_deny
  - ufw.allow_ssh
  - ufw.enable
  - docker
  - dnsmasq
  - sysdig
  - salt.minion.install
  - salt.minion
  - ntp
# other classes in reclass
classes:
  - ufw-allow-ssh
  - reclass
  - pkg
# seeds pillar
parameters:
  foo: bar
