{%- set server_port = salt['pillar.get']('stackage:server:port', 3000) %}
{%- set app_root = salt['pillar.get']('stackage:server:app_root', 'http://beta.stackage.org') %}
{%- set hackage_root = salt['pillar.get']('stackage:server:hackage_root', 'http://hackage.fpcomplete.com') %}
{%- set blob_store_path = salt['pillar.get']('stackage:server:blob_path', '/tmp/stackage-server') %}
{%- set aws_s3_access = salt['pillar.get']('stackage:s3:access', 'someaccesskey') %}
{%- set aws_s3_secret = salt['pillar.get']('stackage:s3:secret', 'somesecretkey') %}
{%- set aws_s3_bucket = salt['pillar.get']('stackage:s3:bucket', 'stackage-server-beta') %}

Default: &defaults
  host: "*4" # any IPv4 host
  port: {{ server_port }}
  approot: {{ app_root }}
  hackage-root: {{ hackage_root }}
  admin-users:
    - fpcomplete
  # google-auth:
    # client-id: foo
    # client-secret: bar

Development:
  <<: *defaults
  blob-store: file:dev-blob-store

Testing:
  <<: *defaults

Staging:
  <<: *defaults
  blob-store:
    type: aws
    local: {{ blob_store_path }}
    access: {{ aws_s3_access }}
    secret: {{ aws_s3_secret }}
    bucket: {{ aws_s3_bucket }}


Production:
  <<: *defaults
  blob-store: file:{{ blob_store_path }}
