Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://beta.stackage.org"
  hackage-root: http://hackage.fpcomplete.com
  admin-users:
    - fpcomplete
  # google-auth:
    # client-id: foo
    # client-secret: bar

Development:
  <<: *defaults
  blob-store: file:dev-blob-store

Testing:
  <<: *defaults

Staging:
  <<: *defaults
  blob-store:
    type: aws
    local: /tmp/stackage-server
    access: someaccesskey
    secret: somesecretkey
    bucket: stackage-server-beta


Production:
  #approot: "http://www.example.com"
  <<: *defaults
  blob-store: file:/tmp/stackage-server

S3-backed storage:
  blob-store:
    type: aws
    local: /tmp/stackage-server
    access: someaccesskey
    secret: somesecretkey
    bucket: stackage-server-beta


