{%- set app_root = 'http://beta.stackage.org' %}
{%- set hackage_root = 'http://hackage.fpcomplete.com' %}
{%- set aws_s3_access  = 'someaccesskey' %}
{%- set aws_s3_secret  = 'somesecretkey' %}
{%- set aws_s3_bucket  = 'stackage-server-beta' %}
{%- set blob_store_path = '/tmp/stackage-server' %}
{%- set server_port = 3000 %}

Default: &defaults
  host: "*4" # any IPv4 host
  port: {{ server_port }}
  approot: {{ app_root }}
  hackage-root: {{ hackage_root }}
  admin-users:
    - fpcomplete
  # google-auth:
    # client-id: foo
    # client-secret: bar

Development:
  <<: *defaults
  blob-store: file:dev-blob-store

Testing:
  <<: *defaults

Staging:
  <<: *defaults
  blob-store:
    type: aws
    local: {{ blob_store_path }}
    access: {{ aws_s3_access }}
    secret: {{ aws_s3_secret }}
    bucket: {{ aws_s3_bucket }}


Production:
  <<: *defaults
  blob-store: file:{{ blob_store_path }}
